https://github.com/Huachao/vscode-restclient

###

# 기본
GET http://localhost:8082 HTTP/1.1
content-type: application/json

###
# 사용자 리스트
GET http://localhost:8082/api/user/all-user HTTP/1.1
content-type: application/json

###
# 테스트 리스트
GET http://localhost:8082/api/user/all-test HTTP/1.1
content-type: application/json

###
# 유저 리스트
GET http://localhost:8082/api/user/user-list HTTP/1.1
content-type: application/json